version: "3.9"


# если нужно из одного сервиса подключиться к другому:
# необходимо в качестве хоста использовать название сервиса (прим. db)
# в качестве порта внутренний порт (прим. 5432)

# если нужно вне докера подключиться к сервису
# необходимо в качестве хоста использовать localhost или 127.0.0.1
# в качестве порта внешний порт (прим. 5433)

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  redis:
    image: redis:alpine

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A hotel worker -l DEBUG -P solo
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - C_FORCE_ROOT=true
    # env_file:
    #   - ./.env
    depends_on:
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A hotel beat -l DEBUG --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/code
    depends_on:
      - redis